version: "3.8"

volumes:
  postgres_volume:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    # image: sh2man/foodgram:v1
    build: .
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    image: nginx:1.19
    restart: always
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static/:ro
      - media_volume:/app/media/
