name: FoodGram

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          cd foodgram
          flake8 --ignore=E501,F401,F403,F405,W503

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sh2man/foodgram:v1

  deploy:
    runs-on: ubuntu-latest
    needs: push_to_docker_hub
    steps:
      - uses: actions/checkout@master

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          rm: true
          source: "./nginx/*,./docker-compose.yaml"
          target: "./foodgram_deploy"

      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        env:
          ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: ENV_FILE
          script: |
            cd foodgram_deploy/
            echo $ENV_FILE |tr ' ' '\n' > .env
            sudo docker pull sh2man/foodgram:v1
            if [ -n "$(sudo docker ps -a -q)" ]; then
                sudo docker stop $(sudo docker ps -a -q)
            fi
            sudo docker-compose up -d
            # sudo docker-compose exec -T web python manage.py collectstatic --no-input
            sudo docker image prune -f

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} успешно выполнен!
